//url list, one list per show.

var photos=[
    "url('/images-news/2005/loft/1.jpg')",
    "url('/images-news/2005/loft/2.jpg')",
    "url('/images-news/2005/loft/3.jpg')",
    "url('/images-news/2005/loft/4.jpg')",
    "url('/images-news/2005/loft/5.jpg')",
    "url('/images-news/2005/loft/6.jpg')",
    "url('/images-news/2005/loft/7.jpg')",
    "url('/images-news/2005/loft/8.jpg')",
    "url('/images-news/2005/loft/9.jpg')",
    "url('/images-news/2005/loft/10.jpg')",
    "url('/images-news/2005/loft/11.jpg')",
    "url('/images-news/2005/loft/12.jpg')",
    "url('/images-news/2005/loft/13.jpg')",
    "url('/images-news/2005/loft/14.jpg')",
    "url('/images-news/2005/loft/15.jpg')",
    "url('/images-news/2005/loft/16.jpg')",
    "url('/images-news/2005/loft/17.jpg')",
    "url('/images-news/2005/loft/18.jpg')",
    "url('/images-news/2005/loft/19.jpg')",
    "url('/images-news/2005/loft/20.jpg')",
    "url('/images-news/2005/loft/21.jpg')",
    "url('/images-news/2005/loft/22.jpg')",
    "url('/images-news/2005/loft/23.jpg')",
    "url('/images-news/2005/loft/24.jpg')",
    "url('/images-news/2005/loft/25.jpg')",
    "url('/images-news/2005/loft/26.jpg')",
    "url('/images-news/2005/loft/27.jpg')",
    "url('/images-news/2005/loft/28.jpg')",
    "url('/images-news/2005/loft/29.jpg')",
    "url('/images-news/2005/loft/30.jpg')",
    "url('/images-news/2005/loft/31.jpg')"
];
// sans titre: mettre ''
var legendes = [
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge',
    'Loft Gallery, 2005 - Doug Petrovic, Roland Erguy, Monique Dussauge'
];

var delai = 3000; // delai between pictures in ms
