//url list, one list per show.

var photos=[
    "url('/images-news/2009/jea/1.jpg')",
    "url('/images-news/2009/jea/2.jpg')",
    "url('/images-news/2009/jea/3.jpg')",
    "url('/images-news/2009/jea/4.jpg')",
    "url('/images-news/2009/jea/5.jpg')",
    "url('/images-news/2009/jea/6.jpg')",
    "url('/images-news/2009/jea/7.jpg')",
    "url('/images-news/2009/jea/8.jpg')",
    "url('/images-news/2009/jea/9.jpg')",
    "url('/images-news/2009/jea/10.jpg')",
    "url('/images-news/2009/jea/11.jpg')",
    "url('/images-news/2009/jea/12.jpg')",
    "url('/images-news/2009/jea/13.jpg')",
    "url('/images-news/2009/jea/14.jpg')",
    "url('/images-news/2009/jea/15.jpg')",
    "url('/images-news/2009/jea/16.jpg')",
    "url('/images-news/2009/jea/17.jpg')",
    "url('/images-news/2009/jea/18.jpg')",
    "url('/images-news/2009/jea/19.jpg')",
    "url('/images-news/2009/jea/20.jpg')",
    "url('/images-news/2009/jea/21.jpg')",
    "url('/images-news/2009/jea/22.jpg')",
    "url('/images-news/2009/jea/23.jpg')",
    "url('/images-news/2009/jea/24.jpg')",
    "url('/images-news/2009/jea/25.jpg')",
    "url('/images-news/2009/jea/26.jpg')",
    "url('/images-news/2009/jea/27.jpg')",
    "url('/images-news/2009/jea/28.jpg')",
    "url('/images-news/2009/jea/29.jpg')",
    "url('/images-news/2009/jea/30.jpg')",
    "url('/images-news/2009/jea/31.jpg')",
    "url('/images-news/2009/jea/32.jpg')",
    "url('/images-news/2009/jea/33.jpg')",
    "url('/images-news/2009/jea/34.jpg')",
    "url('/images-news/2009/jea/35.jpg')",
    "url('/images-news/2009/jea/36.jpg')",
    "url('/images-news/2009/jea/37.jpg')",
    "url('/images-news/2009/jea/38.jpg')",
    "url('/images-news/2009/jea/39.jpg')",
    "url('/images-news/2009/jea/40.jpg')",
    "url('/images-news/2009/jea/41.jpg')"
];
// sans titre: mettre ''
var legendes = [
    'AsF - JEA 2009.... s.v.p. attendez la fin des discours ..',
    'AsF - JEA 2009 - dernières préparations',
    'AsF - JEA - prêt pour l\'attaque',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Idées et plannification d\'abord (en théorie)',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Mères admises en observatrices, uniquement',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Ah oui, les couleurs se mélangent ...',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',

    'les oeuvres des premières groupes prennent forme ...',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'la surface se remplit ..',
    '... et se recouvre ...',
    'Les groupes suivantes entrent en action artistique',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',

    'Les oeuvres de la première groupe sont sèches - les taches et les mains également ...',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Même les organisateurs ne résistent pas au plaisir',
    'Artistes-sf.org - Journée de l\'enfance africaine 2009',
    'Oeuvre 1',
    'Oeuvre 2',
    'Oeuvre 3',
    'Oeuvre 3, vue de l\'autre coté',
    'Oeuvre 4 ... dans les pas de quelques artistes Fluxus'
];

var delai = 3000; // delai between pictures in ms
